apps/dashboard/urls.py
from django.conf.urls import url
from .views import * 
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # URLs de Sesion
    url(r'^$', base, name='dashboard'),
    url(r'^login/$', iniciar, name='login'),
    url(r'^salir/$', salir, name='cerrar_sesion'),
    # URLs de Usuarios Administradores
    url(r'^search/$', BuscarUsuario, name='search'),
    url(r'^permisos/$', login_required(CargarPermisos,login_url='/dashboard/'), name='permisos'),
    url(r'^listuser', login_required(ListarUser.as_view(),login_url='/dashboard/'), name='listar_user'),
    url(r'^crearuser/$', login_required(CrearUser.as_view(),login_url='/dashboard/'), name='crear_user'),
    url(r'^editaruser/(?P<pk>\d+)$', login_required(ModificarUser.as_view(),login_url='/dashboard/'), name='editar_user'),
    url(r'^eliminaruser/(?P<pk>\d+)/$',login_required(EliminarUser.as_view(),login_url='/dashboard/'), name='eliminar_user'),
    # URLs de Usuarios Clientes
    url(r'^searchc/$', BuscarCliente, name='searchc'),
    url(r'^listclientes', login_required(ListarClientes.as_view(),login_url='/dashboard/'), name='listar_clientes'),
    url(r'^crearcliente/$', login_required(CrearCliente.as_view(),login_url='/dashboard/'), name='crear_cliente'),
    url(r'^editarcliente/(?P<pk>\d+)$', login_required(ModificarCliente.as_view(),login_url='/dashboard/'), name='editar_cliente'),
    url(r'^estadocliente/(?P<id>\d+)/$', login_required(EstadoCliente,login_url='/dashboard/'), name='estado_cliente'),
    # URLs de Configuracion Basica
    url(r'^configuracion/$', login_required(CrearConfiguracion.as_view(),login_url='/dashboard/'), name='crear_configuracion'),
    url(r'^configuracion/(?P<pk>\d+)/$', login_required(EditarConfiguracion.as_view(),login_url='/dashboard/'), name='configuracion'),
    # URLs de Marcas
    url(r'^listmarca', login_required(ListarMarcas.as_view(),login_url='/dashboard/'), name='listar_marcas'),
    url(r'^crearmarca/$', login_required(CrearMarcas.as_view(),login_url='/dashboard/'), name='crear_marca'),
    url(r'^editarmarca/(?P<pk>\d+)$', login_required(ModificarMarcas.as_view(),login_url='/dashboard/'), name='editar_marca'),
    url(r'^eliminarmarca/(?P<pk>\d+)/$',login_required(EliminarMarcas.as_view(),login_url='/dashboard/'), name='eliminar_marca'),
    url(r'^cargarmarcas$', login_required(cargar_marcas,login_url='/dashboard/'),name='cargar_marcas'),
    # URLs de Modelos
    url(r'^listmodelo', login_required(ListarModelos.as_view(),login_url='/dashboard/'), name='listar_modelos'),
    url(r'^crearmodelo/$', login_required(CrearModelos.as_view(),login_url='/dashboard/'), name='crear_modelo'),
    url(r'^editarmodelo/(?P<pk>\d+)$', login_required(ModificarModelos.as_view(),login_url='/dashboard/'), name='editar_modelo'),
    url(r'^eliminarmodelo/(?P<pk>\d+)/$',login_required(EliminarModelos.as_view(),login_url='/dashboard/'), name='eliminar_modelo'),
    # URLs de Testimoniales
    url(r'^listartesti', login_required(ListarTestimoniales.as_view(),login_url='/dashboard/'), name='listar_test'),
    url(r'^creartest/$', login_required(CrearTestimonial.as_view(),login_url='/dashboard/'), name='crear_test'),
    url(r'^editartest/(?P<pk>\d+)/$', login_required(ModificarTestimonial.as_view(),login_url='/dashboard/'), name='editar_test'),
    url(r'^estadotest/(?P<id>\d+)/$', login_required(EstadoTestimonial,login_url='/dashboard/'), name='estado_test'),
    url(r'^eliminartest/(?P<pk>\d+)/$',login_required(EliminarTestimonial.as_view(),login_url='/dashboard/'), name='eliminar_test'),
    # URLs de Servicios
    url(r'^listarserv', login_required(ListarServicios.as_view(),login_url='/dashboard/'), name='listar_serv'),
    url(r'^crearserv/$', login_required(CrearServicios.as_view(),login_url='/dashboard/'), name='crear_serv'),
    url(r'^editarserv/(?P<pk>\d+)/$', login_required(EditarServicios.as_view(),login_url='/dashboard/'), name='editar_serv'),
    url(r'^eliminarserv/(?P<pk>\d+)/$',login_required(EliminarServicios.as_view(),login_url='/dashboard/'), name='eliminar_serv'),
    # URLs de Noticias
    url(r'^listarnoti', login_required(ListarNoticias.as_view(),login_url='/dashboard/'), name='listar_noti'),
    url(r'^crearnoti/$', login_required(CrearNoticias.as_view(),login_url='/dashboard/'), name='crear_noti'),
    url(r'^editarnoti/(?P<pk>\d+)/$', login_required(EditarNoticias.as_view(),login_url='/dashboard/'), name='editar_noti'),
    url(r'^estadonoti/(?P<id>\d+)/$', login_required(EstadoNoticias,login_url='/dashboard/'), name='estado_noti'),
    url(r'^eliminarnoti/(?P<pk>\d+)/$',login_required(EliminarNoticias.as_view(),login_url='/dashboard/'), name='eliminar_noti'),
    # URLs de Noticias
    url(r'^listarmsj/', login_required(ListarMensajes.as_view(),login_url='/dashboard/'), name='listar_mensajes'),
    url(r'^vermsj/(?P<id>\d+)/$', login_required(VerMensaje,login_url='/dashboard/'), name='ver_mensaje'),
    url(r'^responder/$', login_required(enviar_respuesta,login_url='/dashboard/'), name='enviar_respuesta'),
    # URLs de Noticias
    url(r'^logos/', login_required(Logos,login_url='/dashboard/'), name='logos'),
    url(r'^logoelim/(?P<id>\d+)/$', login_required(LogosEliminar,login_url='/dashboard/'), name='eliminar_logo'),


    
]

packforward/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from apps.dashboard.views import salir
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
    url(r'^', include('apps.website.urls')),
    url(r'^dashboard/', include('apps.dashboard.urls')),

    url(r'^reset/password_reset', password_reset, 
        {'template_name':'dashboard/restablecer.html',
        'email_template_name': 'dashboard/correo-reestablecer.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'dashboard/enviado-reestablecer.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'dashboard/confirmar-reestablecer.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'dashboard/reestablecida.html'},
        name='password_reset_complete'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

# Create your models here.


class Configuracion(models.Model):
    id_configuracion = models.AutoField(primary_key=True)
    precio_usd = models.DecimalField(max_digits=19, decimal_places=3, default=0.0,
                                     null=False, blank=False, verbose_name=_('precio del dolar en bs.'))
    pago_bs=models.BooleanField(default=False,verbose_name=_('permite precio en bs.'))
    imagen1nosotros=models.ImageField(upload_to='encabezados/', default="",null=False,
                               blank=True, verbose_name=_('imagen nosotros 1'))
    imagen2nosotros=models.ImageField(upload_to='encabezados/', default="",null=False,
                               blank=True, verbose_name=_('imagen nosotros 2'))
    descripcion_nosotros=models.TextField(null=False, blank=False, default="", verbose_name=_('descripción nosotros'))
    imagen1info=models.ImageField(upload_to='encabezados/', default="",null=False,
                               blank=True, verbose_name=_('imagen informacion 1'))
    imagen2info=models.ImageField(upload_to='encabezados/', default="",null=False,
                               blank=True, verbose_name=_('imagen informacion 2'))
    imagen3info=models.ImageField(upload_to='encabezados/', default="",null=False,
                               blank=True, verbose_name=_('imagen informacion 3'))
    descripcion_info=models.TextField(null=False, blank=False, default="", verbose_name=_('descripción informacion'))

    class Meta:
        db_table = 'configuracion'
        verbose_name = 'configuracion'


class Administradores(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    pais = models.CharField(
        max_length=50, null=False, blank=True, verbose_name=_('pais de residencia'))
    ciudad = models.CharField(max_length=50, null=False,
                           blank=True, verbose_name=_('ciudad de residencia'))
    imagen = models.ImageField(upload_to='profile_photo/', default="",null=False,
                               blank=True, verbose_name=_('imagen del administrador'))
    class Meta:
        db_table = 'administradores'
        verbose_name = 'administradores'

class Permisos(models.Model):
    user = models.ForeignKey(User, null=False, blank=False, verbose_name=_('usuario relacionado'))
    permiso = models.IntegerField(null=False, blank=False, default=0, verbose_name=_('permiso asignado'))

    class Meta:
        db_table = 'permisos'
        verbose_name = 'permisos'

class Servicios(models.Model):
    id_servicio = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=50, null=False, blank=False, default=0, verbose_name=_('tipo de servicio'))
    tipo=models.CharField(max_length=5, null=False, blank=False, verbose_name=_('Nombre del servicio'))
    encabezado = models.ImageField(upload_to='encabezados/', default="",null=False,
                               blank=True, verbose_name=_('imagen encabezado'))
    imagen_detalle = models.ImageField(upload_to='encabezados/', default="",null=False,
                               blank=True, verbose_name=_('imagen detalle'))
    descripcion = models.TextField(null=False, blank=False, verbose_name=_('descripción del servicio'))
    descuento = models.DecimalField(max_digits=19,decimal_places=3,default=0.0, null=False, blank=False, verbose_name=_('Descuento en el Servicio'))
    maneja_seguro = models.BooleanField(blank=False, default=False, verbose_name=_('Servicio maneja Seguro'))
    estado = models.BooleanField(blank=False, default=True, verbose_name=_('Estado del Servicio'))
    divisor_pg = models.IntegerField(
        default=0, null=False, blank=False, verbose_name=_('divisor de peso en pulgadas'))
    divisor_cm = models.IntegerField(
        default=0, null=False, blank=False, verbose_name=_('divisor de peso en centimetros'))
    precio_lb = models.DecimalField(max_digits=19, decimal_places=3, default=0.0,
                                    null=False, blank=False, verbose_name=_('precio por libra'))
    precio_kg = models.DecimalField(max_digits=19, decimal_places=3, default=0.0,
                                    null=False, blank=False, verbose_name=_('precio por Kilogramo'))

    class Meta:
        db_table = 'servicios'
        verbose_name = 'servicio'


class LogosClientes(models.Model):
    id_logo = models.AutoField(primary_key=True)
    imagen = models.ImageField(upload_to='logos_clientes/', default="",null=False,
                               blank=True, verbose_name=_('imagen logo'))

    class Meta:
        db_table = 'logos_clientes'
        verbose_name = 'logos clientes'


class SuperCategorias(models.Model):
    id_super = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50, null=False, blank=False, verbose_name=_('nombre de la super categoria'))
    
    class Meta:
        db_table = 'super_categoria'
        verbose_name = 'super categoría'


class Categorias(models.Model):
    id_categoria = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50, null=False, blank=False, verbose_name=_('nombre de la categoria'))
    id_super = models.ForeignKey(SuperCategorias, null=True, blank=True, verbose_name=_('super categoría'))
    
    class Meta:
        db_table = 'categoria'
        verbose_name = 'categoría'


class SubCategorias(models.Model):
    id_subcategoria = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50, null=False, blank=False, verbose_name=_('nombre de la subcategoria'))
    id_categoria = models.ForeignKey(Categorias, null=True, blank=True, verbose_name=_('categoría'))
    
    class Meta:
        db_table = 'subcategoria'
        verbose_name = 'sub categoría'


class Marca(models.Model):
    id_marca = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50,null=False,blank=False,verbose_name=_('nombre de la marca'))

    class Meta:
        db_table = 'marca'
        verbose_name = 'marca'

    def __str__(self):
        return self.nombre


class Modelo(models.Model):
    id_modelo = models.AutoField(primary_key=True)
    id_marca = models.ForeignKey(Marca, null=True, blank=True, verbose_name=_('marca relacionada'))
    nombre = models.CharField(max_length=50,null=False,blank=False,verbose_name=_('nombre del modelo'))

    class Meta:
        db_table = 'modelo'
        verbose_name = 'modelo'


class Productos(models.Model):
    id_producto = models.AutoField(primary_key=True)
    descripcion = models.CharField(max_length=250, null=False, blank=False, verbose_name=_('descripción'))
    id_subcategoria = models.ForeignKey(SubCategorias,null=False,blank=False,default=0,verbose_name=_('categoría relacionada'))
    id_marca = models.ForeignKey(Marca,null=False,blank=False,default=0,verbose_name=_('marca del producto'))
    id_modelo = models.ForeignKey(Modelo,null=False,blank=False,default=0,verbose_name=_('modelo del producto'))
    url_video = models.FileField(upload_to='videos/',null=False,blank=False,verbose_name=_('video descriptivo'))
    fecha_publicacion = models.DateField(auto_now_add=True, editable=True, verbose_name=_('fecha de publicacion del producto'))

    class Meta:
        db_table = 'producto'
        verbose_name = 'producto'


class DetalleProductos(models.Model):
    id_detalle = models.AutoField(primary_key=True)
    id_producto = models.ForeignKey(Productos,null=False,blank=False,default=0,verbose_name=_('producto relacionado'))
    color = models.CharField(max_length=10, null=False, blank=False, verbose_name=_('color del producto'))
    precio = models.DecimalField(max_digits=19,decimal_places=3,default=0.0, null=False, blank=False, verbose_name=_('precio del producto'))
    url_imagen = models.ImageField(upload_to='fotos_productos/',null=False,blank=False,verbose_name=_('video descriptivo'))
    existencia = models.IntegerField(default=0, null=False, blank=False, verbose_name=_('existencia del producto'))
    estado = models.BooleanField(blank=False, default=True, verbose_name=_('estado del producto'))
    
    class Meta:
        db_table = 'detalleproducto'
        verbose_name = 'detalle del producto'


class DireccionFacturacionUsuario(models.Model):
    id_direccion = models.AutoField(primary_key=True)
    id_usuario = models.ForeignKey(
        User, null=True, blank=True, verbose_name=_('usuario relacionado'))
    pais = models.CharField(max_length=50, null=True,
                            blank=True, default='', verbose_name=_('país'))
    estado = models.CharField(max_length=50, null=True,
                              blank=True, default='', verbose_name=_('estado'))
    ciudad = models.CharField(max_length=50, null=True,
                              blank=True, default='', verbose_name=_('ciudad'))
    calle = models.CharField(max_length=50, null=True,
                              blank=True, default='', verbose_name=_('calle'))
    codigo_postal = models.CharField(
        max_length=10, null=True, blank=True, default='', verbose_name=_('codigo postal'))
    telefono = models.CharField(
        max_length=50, null=False, blank=True, verbose_name=_('telefono'))
    telefono2 = models.CharField(
        max_length=50, null=False, blank=True, verbose_name=_('telefono 2s'))

    class Meta:
        db_table = 'direccion_facturacion'
        verbose_name = 'direccion de usuario'


class DireccionEnvioUsuario(models.Model):
    id_direccion = models.AutoField(primary_key=True)
    id_usuario = models.ForeignKey(
        User, null=True, blank=True, verbose_name=_('usuario relacionado'))
    paise = models.CharField(max_length=50, null=True,
                            blank=True, default='', verbose_name=_('país'))
    estadoe = models.CharField(max_length=50, null=True,
                              blank=True, default='', verbose_name=_('estado'))

apps/dashboard/templates/dashboard/configuracion.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
<link rel="stylesheet" href="{% static 'css/froala_editor.min.css' %}">
<link rel="stylesheet" href="{% static 'css/froala_editor.pkgd.min.css' %}">
<link rel="stylesheet" href="{% static 'css/froala_style.min.css' %}">
{% endblock css %}

{% block content %}
     <div class="container whitecanvas" style="margin-top: 20px; margin-left: 20px; width: auto !important">
         <form id="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-md-10 col-md-offset-1">
                <div class="card">
                    <div class="header">
                        <h3 class="title">{% block title %}Configuración de Valores Iniciales{% endblock title %}</h3>
                    </div>
                        <div class="content">
                            <!-- Seccion "NOSOTROS -->
                            <div class="row">
                                <h4 class="title">Seccion "NOSOTROS"</h4>
                                    <div class="form-group col-md-12">
                                        <label>Descripcion:</label>
                                        {{form.descripcion_nosotros}}
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label>Imagen 1:</label>
                                        <img id="preview_image" src="{{imagen}}" class="img-responsive" alt="" style="max-width: 300px; max-height: 100px; width: 300px; height: 100px">
                                        <div class="text-center">
                                            {{form.imagen1nosotros}}
                                            <a id="browse" class="btn" style="border-radius: 20px !important; margin: 20px 0;">Cargar Imagen</a>
                                        </div>
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label>Imagen 2:</label>
                                        <img id="preview_image2" src="{{imagen2}}" class="img-responsive" alt="" style="max-width: 300px; max-height: 100px; width: 300px; height: 100px">
                                        <div class="text-center">
                                            {{form.imagen2nosotros}}
                                            <a id="browse2" class="btn" style="border-radius: 20px !important; margin: 20px 0;">Cargar Imagen</a>
                                        </div>
                                    </div>
                            </div>

                            <!-- >Seccion "INFORMACION -->
                            <div class="row">
                                <h4 class="title">Seccion "INFORMACION"</h4>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Descripcion:</label>
                                        {{form.descripcion_info}}
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Imagen 1:</label>
                                        <img id="preview_image3" src="{{imagen3}}" class="img-responsive" alt="" style="max-width: 250px; max-height: 100px; width: 250px; height: 100px">
                                        <div class="text-center">
                                            {{form.imagen1info}}
                                            <a id="browse3" class="btn" style="border-radius: 20px !important; margin: 20px 0;">Cargar Imagen</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Imagen 2:</label>
                                        <img id="preview_image4" src="{{imagen4}}" class="img-responsive" alt="" style="max-width: 250px; max-height: 100px; width: 250px; height: 100px">
                                        <div class="text-center">
                                            {{form.imagen2info}}
                                            <a id="browse4" class="btn" style="border-radius: 20px !important; margin: 20px 0;">Cargar Imagen</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Imagen 3:</label>
                                        <img id="preview_image5" src="{{imagen5}}" class="img-responsive" alt="" style="max-width: 250px; max-height: 100px; width: 250px; height: 100px">
                                        <div class="text-center">
                                            {{form.imagen3info}}
                                            <a id="browse5" class="btn" style="border-radius: 20px !important; margin: 20px 0;">Cargar Imagen</a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!-- Pagos -->
                            <div class="row text-center">
                                <div class="col-md-5 col-md-offset-1">
                                    <div class="form-group">
                                        <label>Precio USD al Cambio Bs</label>
                                        {{form.precio_usd}}
                                    </div>
                                </div>
                                <div class="col-md-5">
                                    <div class="form-group">
                                        <label>Aceptar pagos en Bolivares</label>
                                        {{form.pago_bs}}
                                    </div>
                                </div>
                            </div>
                            {% if form.errors %}
                                <h6 style="color: red">{{ form.errors }}</h6>
                            {% endif %}
                            {% for message in messages %}
                                <h6 style="color: red">{{ message }}</h6>
                            {% endfor %}
                             <div class="text-center">
                                 <button type="submit" class="btn" style="border-radius: 20px !important;">Guardar Configuración</button>
                             </div>
                        </div>
                    </div>
            </div>
         </form>
     </div>

{% endblock content %}
{% block js %}
<script type="text/javascript" src="{% static 'js/froala_editor.min.js' %}"></script>
<script type="text/javascript">
$(function (){
    $('#browse').click(function(){
        $(this).parent().find('input').click();
    });
    $('#browse2').click(function(){
        $(this).parent().find('input').click();
    });
    $('#browse3').click(function(){
        $(this).parent().find('input').click();
    });
    $('#browse4').click(function(){
        $(this).parent().find('input').click();
    });
    $('#browse5').click(function(){
        $(this).parent().find('input').click();
    });
});

function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
            $('#preview_image').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}

function readURL2(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
            $('#preview_image2').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}

function readURL3(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
            $('#preview_image3').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}

function readURL4(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
            $('#preview_image4').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}

function readURL5(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
            $('#preview_image5').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}

$('#id_descripcion_nosotros').froalaEditor();
$('#id_descripcion_info').froalaEditor();

</script>
 {% endblock js %}

apps/dashboard/templates/dashboard/correo-reestablecer.html
Solicitaste reestablecimiento de contraseña.
Click en el siguiente link para crear una nueva contraseña.
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
Tu nombre de usuario es: {{ user.get_username }}

apps/dashboard/templates/dashboard/eliminar_modelos.html
{% extends 'dashboard/base.html' %}

{% block content %}
<div  style="margin-left: 310px;margin-top: 50px">
	<h3>Confirmar Eliminación</h3>
		<form method="post">
			{% csrf_token %}
				<h4>¿Está seguro que desea eliminar el registro?</h4>
				<button type="submit">Si</button>
				<a href="{% url 'listar_modelos' %}">No</a>
		</form>
</div>		
{% endblock %}

apps/dashboard/templates/dashboard/modificar_noticia.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
<link rel="stylesheet" href="{% static 'css/froala_editor.min.css' %}">
<link rel="stylesheet" href="{% static 'css/froala_editor.pkgd.min.css' %}">
<link rel="stylesheet" href="{% static 'css/froala_style.min.css' %}">
<style>
    .fr-box {margin: 15px 0 !important;}
    .fr-toolbar .fr-command.fr-btn i, .fr-popup .fr-command.fr-btn i {color: black!important;}
</style>
{% endblock css %}

{% block content %}
 <div class="container whitecanvas" style="margin-top: 20px; width: auto; margin-left: 20px;">
     <div class="row">
        <form id="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-md-5" style="padding: 50px">
            <div class="card">
                <div class="header">
                    <h4 class="title">{% block title %}Modificar Noticias{% endblock title %}</h4>
                </div>
                <div class="content">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Titulo</label>
                                {{form.titulo}}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <label>Imagen de la Noticia</label>
                            <img id="preview_image" src="{{imagen}}" class="img-responsive" alt="" style="max-width: 100%; max-height: 200px; width: 100%; height: 200px">
                            <div class="text-center">
                                {{ form.imagen }}
                                <a id="browse" class="btn" style="border-radius: 20px !important; margin: 20px 0;">Cargar Imagen</a>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Información de la Imagen</label>
                                {{form.info_imagen}}
                            </div>
                        </div>
                    </div>
                </div>
                {% if form.errors %}
                    <h6 style="color: red">{{ form.errors }}</h6>
                {% endif %}
            </div>
            </div>
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Contenido Seccion 1</label>
                            {{form.contenido_sec1}}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Contenido Resaltante</label>
                            {{form.contenido_resaltado}}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Contenido Seccion 2</label>
                            {{form.contenido_sec2}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="text-center">
                <button type="submit" class="btn" style="border-radius: 20px !important;">Guardar Noticia</button>
                </div>
        </form>
    </div>
 </div>
{% endblock content %}
{% block js %}
<script type="text/javascript" src="{% static 'js/froala_editor.min.js' %}"></script>
<script type="text/javascript">
    jQuery(document).ready(function () {
        $('#id_contenido_sec1').froalaEditor();
        $('#id_contenido_resaltado').froalaEditor();
        $('#id_contenido_sec2').froalaEditor();
    })
$(function (){
    $('#browse').click(function(){
    $(this).parent().find('input').click();
    });
    $('#browse2').click(function(){
    $(this).parent().find('input').click();
    });
});

function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
            $('#preview_image').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}

function readURL2(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
            $('#preview_image2').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}

function soloNumeros(e) {
  var key = window.Event ? e.which : e.keyCode;
  return ((key >= 48 && key <= 57) || e.keyCode == 9 || e.keyCode == 46)
}

function marcarTipo(){
    $('#id_tipo').val($('#tipo_s').val())
}
</script>
 {% endblock js %}